"""auto-add phone column

Revision ID: 4d849f7f02a2
Revises: 8ceb9c6a94f0
Create Date: 2024-10-21 21:44:06.794741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d849f7f02a2'
down_revision: Union[str, None] = '8ceb9c6a94f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.add_column('posts', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
